# -*- mode: ruby -*-
# vi: set ft=ruby :

PREFIX  = ENV.fetch('PREFIX',  ENV.fetch('PFX', ENV.fetch('X',"fc32")))     # node name prefix
SERVERS = ENV.fetch('SERVERS', ENV.fetch('SRV', ENV.fetch('S',"1"))).to_i   # number of server nodes
WORKERS = ENV.fetch('WORKERS', ENV.fetch('WKR', ENV.fetch('W',"2"))).to_i   # number of agent nodes

K3S_SELINUX = (!['0', 'false'].include?(ENV['K3S_SELINUX'])).to_s           # enable selinux by default
K3S_TOKEN   = ENV['K3S_TOKEN'] || "fedora/32"                                # shared secret for joining
DOCKER      = ['1', 'true'].include?(ENV['DOCKER']).to_s                    # install and enable docker cri?

ENV['K3S_SELINUX'] = K3S_SELINUX
ENV['K3S_TOKEN']   = K3S_TOKEN
ENV['DOCKER']      = DOCKER

Vagrant.configure("2") do |config|
  config.vagrant.plugins = ["vagrant-timezone"]

  config.timezone.value = :host

  config.vm.box = "fedora/32-cloud-base"
  config.vm.box_version = "32.20200422.0"

  ["libvirt", "virtualbox"].each do |p|
    config.vm.provider p do |v, o|
      v.memory = "2048"
      v.cpus = 2
    end
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  SERVERS.times do |i|
    config.vm.define "srv-#{i+1}", primary: i==0 do |node|
      node.vm.hostname = "#{PREFIX}-srv-#{i+1}"
      node.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
        sh.upload_path = "/tmp/vagrant-install-k3s"
        # inject provision-time environment variables
        sh.env = ENV.select{|k,v| k.start_with?('K3S_') || k.start_with?('INSTALL_K3S_')}.merge({
            :INSTALL_K3S_EXEC => "server",
            :INSTALL_K3S_NAME => "server",
            :INSTALL_K3S_SKIP_SELINUX_RPM => "true",
            :INSTALL_K3S_SKIP_START => "true",
            :K3S_KUBECONFIG_MODE => "0644",
        })
        if i == 0 then
            sh.env['K3S_CLUSTER_INIT'] = "true"                     # the first server is special
        else
            sh.env['K3S_URL'] = "https://#{PREFIX}-srv-1:6443"      # the remaining servers are not
        end
        # 1. setup k3s config file
        # 2. augment unit with an exec-start-pre restorecon to guard against naive updates
        # 3. install k3s
        # 4. enable the unit
        sh.inline = <<~SHELL
            #!/usr/bin/env bash
            set -eux -o pipefail
            mkdir -vp /etc/rancher/k3s
            cat << CONF > /etc/rancher/k3s/config.yaml
docker: #{DOCKER}
CONF
            mkdir -vp /etc/systemd/system/k3s-${INSTALL_K3S_NAME}.service.d
            cat << UNIT > /etc/systemd/system/k3s-${INSTALL_K3S_NAME}.service.d/restorecon.conf
[Service]
ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
UNIT
            curl -fsSL https://get.k3s.io | sh
            chmod +x /usr/local/bin/k3s
            systemctl enable --now k3s-${INSTALL_K3S_NAME} || true
        SHELL
      end
    end
  end

  WORKERS.times do |i|
    config.vm.define "wkr-#{i+1}" do |node|
      node.vm.hostname = "#{PREFIX}-wkr-#{i+1}"
      node.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
        sh.upload_path = "/tmp/vagrant-install-k3s"
        # inject provision-time environment variables
        sh.env = ENV.select{|k,v| k.start_with?('K3S_') || k.start_with?('INSTALL_K3S_')}.merge({
            :INSTALL_K3S_EXEC => "agent",
            :INSTALL_K3S_NAME => "agent",
            :INSTALL_K3S_SKIP_SELINUX_RPM => "true",
            :INSTALL_K3S_SKIP_START => "true",
            :K3S_URL => "https://#{PREFIX}-srv-1:6443",
        })
        # 1. setup k3s config file
        # 2. augment unit with an exec-start-pre restorecon to guard against naive updates
        # 3. install k3s
        # 4. enable the unit
        sh.inline = <<~SHELL
            #!/usr/bin/env bash
            set -eux -o pipefail
            mkdir -vp /etc/rancher/k3s
            cat << CONF > /etc/rancher/k3s/config.yaml
docker: #{DOCKER}
CONF
            mkdir -vp /etc/systemd/system/k3s-${INSTALL_K3S_NAME}.service.d
            cat << UNIT > /etc/systemd/system/k3s-${INSTALL_K3S_NAME}.service.d/restorecon.conf
[Service]
ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
UNIT
            curl -fsSL https://get.k3s.io | sh
            chmod +x /usr/local/bin/k3s
            systemctl enable --now k3s-${INSTALL_K3S_NAME} || true
        SHELL
      end
    end
  end

  config.vm.provision "enable-hybrid-cgroups-then-reboot", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-enable-hybrid-cgroups-then-reboot"
    sh.reboot = true
    sh.inline = <<~SHELL
        sudo grubby --update-kernel=ALL --args="systemd.unified_cgroup_hierarchy=0"
    SHELL
  end

  config.vm.provision "disable-swap", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-disable-swap"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        if [ -f /swapfile ]; then
            swapoff -a
            sed -e 's/.*swapfile.*//g' -i /etc/fstab
            rm -vf /swapfile
        fi
    SHELL
  end

  # Disabled by default. To run:
  #   vagrant up --provision-with=upgrade-packages
  # To upgrade only specific packages:
  #   UPGRADE_PACKAGES=container-selinux vagrant up --provision-with=upgrade-packages
  #
  config.vm.provision "upgrade-packages", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-upgrade-packages"
    sh.env = {
        'UPGRADE_PACKAGES': ENV['UPGRADE_PACKAGES'],
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        yum -y upgrade ${UPGRADE_PACKAGES}
    SHELL
  end

  # To re-run, installing CNI from RPM:
  #   INSTALL_PACKAGES="containernetworking-plugins" vagrant up --provision-with=install-packages
  #
  config.vm.provision "install-packages", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-install-packages"
    sh.env = {
        'INSTALL_PACKAGES': ENV['INSTALL_PACKAGES'] || "https://github.com/k3s-io/k3s-selinux/releases/download/v0.4-rc1.testing.1/k3s-selinux-0.4.rc1-1.el8.noarch.rpm",
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        rpm --import https://rpm-testing.rancher.io/public.key
        rpm --import https://rpm.rancher.io/public.key
        yum -y install \
            curl \
            iptables \
            less \
            lsof \
            socat \
            ${INSTALL_PACKAGES}
    SHELL
  end

  # SELinux is Enforcing by default.
  # To set SELinux as Disabled on a VM that has already been provisioned:
  #   SELINUX=Disabled vagrant up --provision-with=selinux
  # To set SELinux as Permissive on a VM that has already been provsioned
  #   SELINUX=Permissive vagrant up --provision-with=selinux
  config.vm.provision "selinux", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-selinux"
    sh.env = {
        'SELINUX': ENV['SELINUX'] || "Enforcing"
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail

        if ! type -p getenforce setenforce &>/dev/null; then
          echo SELinux is Unsupported
          exit 0
        fi

        case "${SELINUX}" in
          Disabled)
            if mountpoint -q /sys/fs/selinux; then
              setenforce 0
              umount -v /sys/fs/selinux
            fi
            ;;
          Enforcing)
            mountpoint -q /sys/fs/selinux || mount -o rw,relatime -t selinuxfs selinuxfs /sys/fs/selinux
            setenforce 1
            ;;
          Permissive)
            mountpoint -q /sys/fs/selinux || mount -o rw,relatime -t selinuxfs selinuxfs /sys/fs/selinux
            setenforce 0
            ;;
          *)
            echo "SELinux mode not supported: ${SELINUX}" >&2
            exit 1
            ;;
        esac
        sestatus -v
    SHELL
  end

  config.vm.provision "install-docker", type: "shell", run: (DOCKER == "true" ? "once" : "never") do |sh|
    sh.upload_path = "/tmp/vagrant-install-docker"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        dnf -y install dnf-plugins-core
        dnf config-manager --add-repo https://download.docker.com/linux/fedora/docker-ce.repo
        dnf -y install \
            containerd.io \
            docker-ce \
            docker-ce-cli
        mkdir -vp /etc/docker
        cat <<-EOF >/etc/docker/daemon.json
{
  "log-driver": "json-file",
  "log-opts": {
    "max-size": "100m"
  },
  "selinux-enabled": #{K3S_SELINUX},
  "storage-driver": "overlay2",
  "storage-opts": [
    "overlay2.override_kernel_check=true"
  ]
}
EOF
        mkdir -vp /usr/lib/systemd/system/docker.service.d
        cat <<-EOF > /usr/lib/systemd/system/docker.service.d/00-local.conf
[Service]
ExecStartPre=-/sbin/modprobe br_netfilter
ExecStartPre=-/sbin/sysctl -w net.bridge.bridge-nf-call-iptables=1
ExecStartPre=-/sbin/sysctl -w net.bridge.bridge-nf-call-ip6tables=1
ExecStartPre=-/sbin/sysctl -w net.ipv4.conf.all.forwarding=1
ExecStartPre=-/sbin/sysctl -w net.ipv6.conf.all.forwarding=1
EOF
        systemctl enable --now docker
    SHELL
  end

  config.vm.provision "install-suc", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-install-suc"
    sh.env = {
        'SUC_MANIFEST_URL': ENV['SUC_MANIFEST_URL'] || "https://github.com/rancher/system-upgrade-controller/releases/download/v0.7.5/system-upgrade-controller.yaml",
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        while ! /usr/local/bin/kubectl get node &>/dev/null; do
            sleep 5
        done
        curl -fsSL ${SUC_MANIFEST_URL} | /usr/local/bin/kubectl apply -f-
    SHELL
  end

  config.vm.provision "install-suc-plans", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-install-suc-plans"
    sh.env = {
        'UPGRADE_K3S_VERSION': ENV['UPGRADE_K3S_VERSION'],
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        while ! /usr/local/bin/kubectl get node &>/dev/null; do
            sleep 5
        done
        cat << EOF > k3s-upgrade.yaml
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  version: ${UPGRADE_K3S_VERSION}
  nodeSelector:
    matchExpressions:
      - {key: k3s.io/upgrade, operator: In, values: ["true", "enabled"]}
      - {key: node-role.kubernetes.io/master, operator: Exists}
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 2
  version: ${UPGRADE_K3S_VERSION}
  nodeSelector:
    matchExpressions:
      - {key: k3s.io/upgrade, operator: In, values: ["true", "enabled"]}
      - {key: node-role.kubernetes.io/master, operator: DoesNotExist}
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  drain:
    force: true
    skipWaitForDeleteTimeout: 30
  upgrade:
    image: rancher/k3s-upgrade
EOF
        while ! /usr/local/bin/kubectl apply -f k3s-upgrade.yaml; do
            sleep 5
        done
    SHELL
  end

  config.vm.provision "upgrade-cluster", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-upgrade-cluster"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        while ! /usr/local/bin/kubectl get node &>/dev/null; do
            sleep 5
        done
        /usr/local/bin/kubectl label node --all k3s.io/upgrade=enabled --overwrite=true
    SHELL
  end

end
