# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  #config.vagrant.plugins = ['vagrant-vbguest']
  #config.vbguest.auto_update = true

  config.vm.box = "dweomer/centos-8"
  config.vm.box_url = "https://cloud.centos.org/centos/8/x86_64/images/CentOS-8-Vagrant-8.2.2004-20200611.2.x86_64.vagrant-virtualbox.box"
  #config.vm.box_version = "2004"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder ".", "/vagrant", disabled: true

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
  end

  config.vm.provision "shell", name: "UPGRADE", inline: <<-SHELL
    set -x
    yum -y upgrade
  SHELL

  config.vm.provision "shell", name: "INSTALL", inline: <<-SHELL
    set -x
    yum -y install \
        curl \
        git \
        less \
        selinux-policy \
        vim \
        wget
  SHELL

  config.vm.provision "shell", name: "CLEANUP", inline: <<-SHELL
    set -x
    yum -y clean all
  SHELL

end
