# -*- mode: ruby -*-
# vi: set ft=ruby :

# 1. Download SLES 15sp3 vagrant box from https://www.suse.com/download/sles/
# 2. Add the box to your vagrant installation:
#    vagrant box add --name sles15sp3 ~/Downloads/SLES15-SP3-Vagrant.x86_64-15.3-libvirt-PublicRC.vagrant.libvirt.box
# 3. SLES_REGCODE=<sles regcode> MICRO_REGCODE=<microos regcode> vagrant up

SERVER = ENV['SERVER'] || "sles-srv"
WORKER = ENV['WORKER'] || "sles-wkr"

Vagrant.configure("2") do |config|
  config.vm.box = "sles15sp3"

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  config.vm.provider :virtualbox do |v|
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.provider :libvirt do |v|
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.synced_folder '.', '/vagrant', disabled: true

  config.vm.provision "register", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-register"
    sh.env = {
        'SLES_REGCODE': ENV['SLES_REGCODE'],
        'MICRO_REGCODE': ENV['MICRO_REGCODE'],
        'MICRO_PRODUCT': ENV['MICRO_PRODUCT'] || "SUSE-MicroOS/5.1/x86_64",
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        SUSEConnect -r "${SLES_REGCODE}"
        SUSEConnect -r "${MICRO_REGCODE}" -p "${MICRO_PRODUCT}" || true
    SHELL
  end

  config.vm.provision "packages", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-packages"
    sh.env = {
        'PACKAGES': ENV['PACKAGES'] || "https://github.com/dweomer/k3s-selinux/releases/download/v0.5.testing.1/k3s-selinux-0.5-1.sle.noarch.rpm",
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        zypper update --repo SUSE-MicroOS-5.1-Pool --no-confirm
        zypper install --repo SUSE-MicroOS-5.1-Pool --no-confirm --allow-unsigned-rpm \
            audit \
            bash \
            curl \
            iptables \
            less \
            lsof \
            patterns-microos-selinux \
            policycoreutils-python-utils \
            systemd \
            ${INSTALL_PACKAGES}
    SHELL
  end

  config.vm.provision "selinux-init", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-selinux-init"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        sed -r 's/(GRUB_CMDLINE_LINUX_DEFAULT)[=]["](.*)["]/\\1="\\2 security=selinux selinux=1"/g' -i.orig /etc/default/grub
        grub2-mkconfig -o /boot/grub2/grub.cfg
    SHELL
  end
  config.vm.provision "selinux-init-reload", type: "reload", run: "once"

  config.vm.provision "selinux-prep", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-selinux-prep"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        restorecon -R /
        sestatus -v
        truncate /var/log/audit/audit.log --reference /dev/null
        sed -e 's/SELINUX=.*/SELINUX=enforcing/g' -i.orig /etc/selinux/config
    SHELL
  end
  config.vm.provision "selinux-prep-reload", type: "reload", run: "once"

  # SELinux is Enforcing by default.
  # To set SELinux as Disabled on a VM that has already been provisioned:
  #   SELINUX=Disabled vagrant up --provision-with=selinux
  # To set SELinux as Permissive on a VM that has already been provsioned
  #   SELINUX=Permissive vagrant up --provision-with=selinux
  config.vm.provision "selinux", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-selinux"
    sh.env = {
        'SELINUX': ENV['SELINUX'] || "Enforcing"
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        if ! type -p getenforce setenforce &>/dev/null; then
          echo SELinux is Unsupported
          exit 0
        fi
        case "${SELINUX}" in
          Disabled)
            if mountpoint -q /sys/fs/selinux; then
              setenforce 0
              umount -v /sys/fs/selinux
            fi
            ;;
          Enforcing)
            mountpoint -q /sys/fs/selinux || mount -o rw,relatime -t selinuxfs selinuxfs /sys/fs/selinux
            setenforce 1
            ;;
          Permissive)
            mountpoint -q /sys/fs/selinux || mount -o rw,relatime -t selinuxfs selinuxfs /sys/fs/selinux
            setenforce 0
            ;;
          *)
            echo "SELinux mode not supported: ${SELINUX}" >&2
            exit 1
            ;;
        esac
        sestatus -v
    SHELL
  end

  (1..3).each do |i|
    config.vm.define "#{SERVER}-#{i}" do |node|
      node.vm.hostname = "#{SERVER}-#{i}"
      node.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
        sh.upload_path = "/tmp/vagrant-install-k3s"
        sh.env = {
            'INSTALL_K3S_CHANNEL': ENV['INSTALL_K3S_CHANNEL'] || "stable",
            'INSTALL_K3S_EXEC': "server",
            'INSTALL_K3S_SKIP_START': "true",
            'K3S_SELINUX': "true",
            'K3S_TOKEN': "sles15sp3",
            'K3S_KUBECONFIG_MODE': "0644",
        }
        if i == 1 then
            sh.env['K3S_CLUSTER_INIT'] = "true"
        else
            sh.env['K3S_URL'] = "https://#{SERVER}-1:6443"
        end
        sh.inline = <<~SHELL
            #!/usr/bin/env bash
            set -eux -o pipefail
            mkdir -vp /etc/systemd/system/k3s.service.d
            cat << EOF > /etc/systemd/system/k3s.service.d/restorecon.conf
[Service]
ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
EOF
            curl -fsSL https://get.k3s.io | sh
            chmod +x /usr/local/bin/k3s
            systemctl enable --now k3s || true
        SHELL
      end
    end
  end

  (1..3).each do |i|
    config.vm.define "#{WORKER}-#{i}" do |node|
      node.vm.hostname = "#{WORKER}-#{i}"
      node.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
        sh.upload_path = "/tmp/vagrant-install-k3s"
        sh.env = {
            'INSTALL_K3S_CHANNEL': ENV['INSTALL_K3S_CHANNEL'] || "stable",
            'INSTALL_K3S_EXEC': "agent",
            'INSTALL_K3S_SKIP_START': "true",
            'K3S_SELINUX': "true",
            'K3S_TOKEN': "sles15sp3",
            'K3S_URL': "https://#{SERVER}-1:6443",
        }
        sh.inline = <<~SHELL
            #!/usr/bin/env bash
            set -eux -o pipefail
            mkdir -vp /etc/systemd/system/k3s-agent.service.d
            cat << EOF > /etc/systemd/system/k3s-agent.service.d/restorecon.conf
[Service]
ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
EOF
            curl -fsSL https://get.k3s.io | sh
            chmod +x /usr/local/bin/k3s
            systemctl enable --now k3s-agent || true
        SHELL
      end
    end
  end

end
