# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # The most common configuration options are documented and commented below.
  # For a complete reference, please see the online documentation at
  # https://docs.vagrantup.com.

  #config.vagrant.plugins = ['vagrant-vbguest']
  #config.vbguest.auto_update = true

  config.vm.box = "dweomer/centos-8"
  config.vm.box_version = "2004"

  # Share an additional folder to the guest VM. The first argument is
  # the path on the host to the actual folder. The second argument is
  # the path on the guest to mount the folder. And the optional third
  # argument is a set of non-required options.
  # config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "/go", "/go"

  if Vagrant.has_plugin?("vagrant-timezone")
    config.timezone.value = :host
  end

  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vm.provider "virtualbox" do |vb|
      vb.gui = false
      vb.cpus = 2
      vb.memory = "2048"
      vb.customize ["modifyvm", :id, "--audio", "none"]
    end
  end

  config.vm.provision "shell", name: "UPGRADE", inline: <<-SHELL
    set -x
    yum -y upgrade
    mkdir -vp /usr/share/vagrant
    chown -v vagrant:vagrant /usr/share/vagrant
  SHELL

  config.vm.provision "file", source: "install-devel-base.sh", destination: "/usr/share/vagrant/install-devel-base.sh"
  config.vm.provision "shell", name: "INSTALL DEVEL: BASE", inline: <<-SHELL
    bash -ex /usr/share/vagrant/install-devel-base.sh
  SHELL

  config.vm.provision "file", source: "install-devel-golang.sh", destination: "/usr/share/vagrant/install-devel-golang.sh"
  config.vm.provision "shell", name: "INSTALL GOLANG", inline: <<-SHELL
    bash -ex /usr/share/vagrant/install-devel-golang.sh
  SHELL

  config.vm.provision "file", source: "install-devel-ginkgo.sh", destination: "/usr/share/vagrant/install-devel-ginkgo.sh"
  config.vm.provision "shell", name: "INSTALL GINKGO", inline: <<-SHELL
    bash -ex /usr/share/vagrant/install-devel-ginkgo.sh
  SHELL

  config.vm.provision "file", source: "install-devel-critools.sh", destination: "/usr/share/vagrant/install-devel-critools.sh"
  config.vm.provision "shell", name: "INSTALL CRI-TOOLS", inline: <<-SHELL
    bash -ex /usr/share/vagrant/install-devel-critools.sh
  SHELL

  config.vm.provision "file", source: "install-devel-crio.sh", destination: "/usr/share/vagrant/install-devel-crio.sh"
  config.vm.provision "file", source: "install-devel-k3s.sh", destination: "/usr/share/vagrant/install-devel-k3s.sh"

end
