# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  config.vm.provider :virtualbox do |v|
    config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.VirtualBox.box"
    v.memory = 2048
    v.cpus = 2
  end
  config.vm.provider :libvirt do |v|
    config.vm.box_url = "https://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-2004_01.LibVirt.box"
    v.memory = 2048
    v.cpus = 2
  end

  config.vm.provision "disable-swap", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-disable-swap"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        if [ -f /swapfile ]; then
            swapoff -a
            sed -e 's/.*swapfile.*//g' -i /etc/fstab
            rm -vf /swapfile
        fi
    SHELL
  end

  # Disabled by default. To run:
  #   vagrant up --provision-with=upgrade-packages
  # To upgrade only specific packages:
  #   UPGRADE_PACKAGES=selinux vagrant up --provision-with=upgrade-packages
  #
  config.vm.provision "upgrade-packages", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-upgrade-packages"
    sh.env = {
        'UPGRADE_PACKAGES': ENV['UPGRADE_PACKAGES'],
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        yum -y upgrade ${UPGRADE_PACKAGES}
    SHELL
  end

  # To re-run, installing CNI from RPM:
  #   INSTALL_PACKAGES="containernetworking-plugins" vagrant up --provision-with=install-packages
  #
  config.vm.provision "install-packages", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-install-packages"
    sh.env = {
        'INSTALL_PACKAGES': ENV['INSTALL_PACKAGES'],
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        yum -y install \
            container-selinux \
            curl \
            iptables \
            less \
            lsof \
            ${INSTALL_PACKAGES}
    SHELL
  end

  # SELinux is Enforcing by default.
  # To set SELinux as Disabled on a VM that has already been provisioned:
  #   SELINUX=Disabled vagrant up --provision-with=selinux
  # To set SELinux as Permissive on a VM that has already been provsioned
  #   SELINUX=Permissive vagrant up --provision-with=selinux
  config.vm.provision "selinux", type: "shell", run: "once" do |sh|
    sh.upload_path = "/tmp/vagrant-selinux"
    sh.env = {
        'SELINUX': ENV['SELINUX'] || "Enforcing"
    }
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail

        if ! type -p getenforce setenforce &>/dev/null; then
          echo SELinux is Disabled
          exit 0
        fi

        case "${SELINUX}" in
          Disabled)
            if mountpoint -q /sys/fs/selinux; then
              setenforce 0
              umount -v /sys/fs/selinux
            fi
            ;;
          Enforcing)
            mountpoint -q /sys/fs/selinux || mount -o rw,relatime -t selinuxfs selinuxfs /sys/fs/selinux
            setenforce 1
            ;;
          Permissive)
            mountpoint -q /sys/fs/selinux || mount -o rw,relatime -t selinuxfs selinuxfs /sys/fs/selinux
            setenforce 0
            ;;
          *)
            echo "SELinux mode not supported: ${SELINUX}" >&2
            exit 1
            ;;
        esac

        echo SELinux is $(getenforce)
    SHELL
  end

  config.vm.provision "install-suc", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-install-suc"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        while ! /usr/local/bin/kubectl get node &>/dev/null; do
            sleep 5
        done
        curl -fsSL https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml | /usr/local/bin/kubectl apply -f-
    SHELL
  end

  config.vm.provision "install-plans", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-install-plans"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        while ! /usr/local/bin/kubectl get node &>/dev/null; do
            sleep 5
        done
        cat << EOF > k3s-upgrade.yaml
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-server
  namespace: system-upgrade
  labels:
    k3s-upgrade: server
spec:
  concurrency: 1
  version: v1.19.1-rc1+k3s1
  nodeSelector:
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
      - {key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: k3s.io/hostname, operator: Exists}
      - {key: k3os.io/mode, operator: DoesNotExist}
      - {key: node-role.kubernetes.io/master, operator: In, values: ["true"]}
  serviceAccountName: system-upgrade
  cordon: true
  upgrade:
    image: rancher/k3s-upgrade
---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: system-upgrade
  labels:
    k3s-upgrade: agent
spec:
  concurrency: 2
  version: v1.19.1-rc1+k3s1
  nodeSelector:
    matchExpressions:
      - {key: k3s-upgrade, operator: Exists}
      - {key: k3s-upgrade, operator: NotIn, values: ["disabled", "false"]}
      - {key: k3s.io/hostname, operator: Exists}
      - {key: k3os.io/mode, operator: DoesNotExist}
      - {key: node-role.kubernetes.io/master, operator: NotIn, values: ["true"]}
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/k3s-upgrade
    args: ["prepare", "k3s-server"]
  drain:
    force: true
    skipWaitForDeleteTimeout: 30
  upgrade:
    image: rancher/k3s-upgrade
EOF
        while ! /usr/local/bin/kubectl apply -f k3s-upgrade.yaml; do
            sleep 5
        done
    SHELL
  end

  config.vm.provision "upgrade-cluster", type: "shell", run: "never" do |sh|
    sh.upload_path = "/tmp/vagrant-upgrade-cluster"
    sh.inline = <<~SHELL
        #!/usr/bin/env bash
        set -eux -o pipefail
        while ! /usr/local/bin/kubectl get node &>/dev/null; do
            sleep 5
        done
        /usr/local/bin/kubectl label node -l 'node-role.kubernetes.io/master==true' k3s-upgrade=server --overwrite=true
        /usr/local/bin/kubectl label node -l 'node-role.kubernetes.io/master!=true' k3s-upgrade=agent  --overwrite=true
    SHELL
  end

  config.vm.define "kay-three-ess-1" do |cluster|
      cluster.vm.hostname = "kay-three-ess-1"
      cluster.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
        sh.upload_path = "/tmp/vagrant-install-k3s"
        sh.env = {
            'INSTALL_K3S_CHANNEL': ENV['INSTALL_K3S_CHANNEL'] || "stable",
            'K3S_KUBECONFIG_MODE': "0644",
            'K3S_SELINUX': "true",
            'K3S_TOKEN': "centos/7",
        }
        sh.inline = <<~SHELL
            #!/usr/bin/env bash
            set -eux -o pipefail
            yum -y install https://rpm.rancher.io/k3s-selinux-0.1.1-rc2.el7.noarch.rpm
            mkdir -vp /etc/systemd/system/k3s.service.d
            cat << EOF > /etc/systemd/system/k3s.service.d/restorecon.conf
[Service]
ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
EOF
            curl -fsSL https://get.k3s.io | sh
        SHELL
      end
  end

  config.vm.define "kay-three-ess-2" do |cluster|
      cluster.vm.hostname = "kay-three-ess-2"
      cluster.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
        sh.upload_path = "/tmp/vagrant-install-k3s"
        sh.env = {
            'INSTALL_K3S_CHANNEL': ENV['INSTALL_K3S_CHANNEL'] || "latest",
            'K3S_SELINUX': "true",
            'K3S_TOKEN': "centos/7",
            'K3S_URL': "https://kay-three-ess-1:6443",
        }
        sh.inline = <<~SHELL
            #!/usr/bin/env bash
            set -eux -o pipefail
            yum -y install https://rpm.rancher.io/k3s-selinux-0.1.1-rc2.el7.noarch.rpm
            mkdir -vp /etc/systemd/system/k3s-agent.service.d
            cat << EOF > /etc/systemd/system/k3s-agent.service.d/restorecon.conf
[Service]
ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
EOF
            curl -fsSL https://get.k3s.io | sh
        SHELL
      end
  end

  config.vm.define "kay-three-ess-3" do |cluster|
      cluster.vm.hostname = "kay-three-ess-3"
      cluster.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
        sh.upload_path = "/tmp/vagrant-install-k3s"
        sh.env = {
            'INSTALL_K3S_CHANNEL': ENV['INSTALL_K3S_CHANNEL'] || "latest",
            'K3S_SELINUX': "true",
            'K3S_TOKEN': "centos/7",
            'K3S_URL': "https://kay-three-ess-1:6443",
        }
        sh.inline = <<~SHELL
            #!/usr/bin/env bash
            set -eux -o pipefail
            yum -y install https://rpm.rancher.io/k3s-selinux-0.1.1-rc2.el7.noarch.rpm
            mkdir -vp /etc/systemd/system/k3s-agent.service.d
            cat << EOF > /etc/systemd/system/k3s-agent.service.d/restorecon.conf
[Service]
ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
EOF
            curl -fsSL https://get.k3s.io | sh
        SHELL
      end
  end

#   config.vm.define "kay-three-ess-4" do |cluster|
#       cluster.vm.hostname = "kay-three-ess-4"
#       cluster.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
#         sh.upload_path = "/tmp/vagrant-install-k3s"
#         sh.env = {
#             'INSTALL_K3S_CHANNEL': ENV['INSTALL_K3S_CHANNEL'] || "latest",
#             'K3S_SELINUX': "true",
#             'K3S_TOKEN': "centos/7",
#             'K3S_URL': "https://kay-three-ess-1:6443",
#         }
#         sh.inline = <<~SHELL
#             #!/usr/bin/env bash
#             set -eux -o pipefail
#             yum -y install https://rpm.rancher.io/k3s-selinux-0.1.1-rc2.el7.noarch.rpm
#             mkdir -vp /etc/systemd/system/k3s-agent.service.d
#             cat << EOF > /etc/systemd/system/k3s-agent.service.d/restorecon.conf
# [Service]
# ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
# EOF
#             curl -fsSL https://get.k3s.io | sh
#         SHELL
#       end
#   end

#   config.vm.define "kay-three-ess-5" do |cluster|
#       cluster.vm.hostname = "kay-three-ess-5"
#       cluster.vm.provision "install-k3s", type: "shell", run: "once" do |sh|
#         sh.upload_path = "/tmp/vagrant-install-k3s"
#         sh.env = {
#             'INSTALL_K3S_CHANNEL': ENV['INSTALL_K3S_CHANNEL'] || "latest",
#             'K3S_SELINUX': "true",
#             'K3S_TOKEN': "centos/7",
#             'K3S_URL': "https://kay-three-ess-1:6443",
#         }
#         sh.inline = <<~SHELL
#             #!/usr/bin/env bash
#             set -eux -o pipefail
#             yum -y install https://rpm.rancher.io/k3s-selinux-0.1.1-rc2.el7.noarch.rpm
#             mkdir -vp /etc/systemd/system/k3s-agent.service.d
#             cat << EOF > /etc/systemd/system/k3s-agent.service.d/restorecon.conf
# [Service]
# ExecStartPre=-/sbin/restorecon /usr/local/bin/k3s
# EOF
#             curl -fsSL https://get.k3s.io | sh
#         SHELL
#       end
#   end

end
